"""Add Project entity

Revision ID: 265773d7ffea
Revises: 002
Create Date: 2026-05-02 23:44:18.720190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '265773d7ffea'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bigenia'
    )
    op.drop_constraint(op.f('conversation_messages_session_id_fkey'), 'conversation_messages', schema='bigenia', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_messages', 'sessions', ['session_id'], ['id'], source_schema='bigenia', referent_schema='bigenia', ondelete='CASCADE')
    op.add_column('generation_results', sa.Column('project_id', sa.UUID(), nullable=True), schema='bigenia')
    op.drop_constraint(op.f('generation_results_session_id_fkey'), 'generation_results', schema='bigenia', type_='foreignkey')
    op.create_foreign_key(None, 'generation_results', 'projects', ['project_id'], ['id'], source_schema='bigenia', referent_schema='bigenia', ondelete='SET NULL')
    op.create_foreign_key(None, 'generation_results', 'sessions', ['session_id'], ['id'], source_schema='bigenia', referent_schema='bigenia', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generation_results', schema='bigenia', type_='foreignkey')
    op.drop_constraint(None, 'generation_results', schema='bigenia', type_='foreignkey')
    op.create_foreign_key(op.f('generation_results_session_id_fkey'), 'generation_results', 'sessions', ['session_id'], ['id'], source_schema='bigenia', referent_schema='bigenia', ondelete='CASCADE')
    op.drop_column('generation_results', 'project_id', schema='bigenia')
    op.drop_constraint(None, 'conversation_messages', schema='bigenia', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_messages_session_id_fkey'), 'conversation_messages', 'sessions', ['session_id'], ['id'], source_schema='bigenia', referent_schema='bigenia', ondelete='CASCADE')
    op.drop_table('projects', schema='bigenia')
    # ### end Alembic commands ###
