"""Add Project entity

Revision ID: 265773d7ffea
Revises: 002
Create Date: 2026-05-02 23:44:18.720190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '265773d7ffea'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bigenia'
    )
    op.drop_table('alembic_version')
    op.alter_column('conversation_messages', 'role',
               existing_type=postgresql.ENUM('user', 'system', name='message_role_enum'),
               type_=sa.Enum('user', 'system', name='message_role_enum', schema='bigenia'),
               existing_nullable=False)
    op.alter_column('conversation_messages', 'response_type',
               existing_type=postgresql.ENUM('visualization', 'clarification', 'message', name='response_type_enum'),
               type_=sa.Enum('visualization', 'clarification', 'message', name='response_type_enum', schema='bigenia'),
               existing_nullable=True)
    op.drop_constraint(op.f('conversation_messages_session_id_fkey'), 'conversation_messages', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_messages', 'sessions', ['session_id'], ['id'], source_schema='bigenia', referent_schema='bigenia', ondelete='CASCADE')
    op.add_column('generation_results', sa.Column('project_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('generation_results_session_id_fkey'), 'generation_results', type_='foreignkey')
    op.create_foreign_key(None, 'generation_results', 'projects', ['project_id'], ['id'], source_schema='bigenia', referent_schema='bigenia', ondelete='SET NULL')
    op.create_foreign_key(None, 'generation_results', 'sessions', ['session_id'], ['id'], source_schema='bigenia', referent_schema='bigenia', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generation_results', schema='bigenia', type_='foreignkey')
    op.drop_constraint(None, 'generation_results', schema='bigenia', type_='foreignkey')
    op.create_foreign_key(op.f('generation_results_session_id_fkey'), 'generation_results', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('generation_results', 'project_id')
    op.drop_constraint(None, 'conversation_messages', schema='bigenia', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_messages_session_id_fkey'), 'conversation_messages', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversation_messages', 'response_type',
               existing_type=sa.Enum('visualization', 'clarification', 'message', name='response_type_enum', schema='bigenia'),
               type_=postgresql.ENUM('visualization', 'clarification', 'message', name='response_type_enum'),
               existing_nullable=True)
    op.alter_column('conversation_messages', 'role',
               existing_type=sa.Enum('user', 'system', name='message_role_enum', schema='bigenia'),
               type_=postgresql.ENUM('user', 'system', name='message_role_enum'),
               existing_nullable=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_table('projects', schema='bigenia')
    # ### end Alembic commands ###
