"""add_query_vectors_table

Revision ID: a3d9bf95cf61
Revises: 544e4d37b715
Create Date: 2026-05-09 02:50:42.638864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'a3d9bf95cf61'
down_revision: Union[str, None] = '544e4d37b715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS bigenia")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # Forzamos el search_path para esta sesión de migración
    op.execute("SET search_path TO bigenia, public")
    op.create_table('query_vectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bigenia'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_vectors', schema='bigenia')
    # ### end Alembic commands ###
