"""add_cached_response_to_query_vectors

Revision ID: a633aea923e9
Revises: a3d9bf95cf61
Create Date: 2026-05-09 03:55:36.290690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a633aea923e9'
down_revision: Union[str, None] = 'a3d9bf95cf61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_vectors', sa.Column('cached_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='bigenia')
    op.add_column('query_vectors', sa.Column('response_type', sa.String(length=50), nullable=True), schema='bigenia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_vectors', 'response_type', schema='bigenia')
    op.drop_column('query_vectors', 'cached_response', schema='bigenia')
    # ### end Alembic commands ###
